template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "saki1248"
__REPO__ = "lang-skf"
__UND2C__ = "skf"
__UNDEFINED__ = "Sakirabiá"
__UND__ = "skf"
