[package]
name = "skf"
human_name = "Sakirabiá"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.skf]
filename = "skf-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-skf"
platform = "windows"
uuid = "70614A0D-973A-4119-B4E9-70D40CC342A7"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.skf"
package = "speller-skf"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-skf-mso"
platform = "windows"
uuid = "E3BD8A83-5A60-4376-A3CB-122AB59C622A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-skf"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
